#!/usr/bin/python
trouve = False
NbDoublon = 0
nbrListe = ["Mirta Torres",
"Sylvie Flepp",
"Roland Marci",
"Michel Cordes",
"Sophie Corcel",
"Marine Danaux",
"Gabriel Riva",
"Joakim Latzko",
"Thomas Marci",
"Laurent Kerusoré",
"Luna Torres",
"Anna Décis",
"Kilian Corcel",
"Tim Rousseau",
"Lola Corcel",
"Marie Mallia",
"Baptiste Marci",
"Thérèse Marci",
"Léo Castelli",
"Pierre Martot",
"Caroline Evenot",
"Sophie de La Rochefoucauld",
"Jérôme Evenot",
"Pierre Gérard",
"Barbara Evenot",
"Léa François",
"Arnaud Mougin",
"Renaud Roussel",
"Claire Mougin",
"Vanessa Valence",
"Océane Mougin",
"Alexia Fourmond",
"Jean-Louis Lieber",
"Roland Marchisio",
"Francesco Ibaldi",
"Emanuele Giorgi",
"Sylvia",
"Roxane Turmel",
"Annabelle Tessin",
"Géraldine Loup",
"Claudia Ragni",
"Margherita Oscuro",
"Arthur Lieber",
"Thomas Lenoir",
"Margaux Lieber",
"Alicia Hava",
"Mélanie Rinato",
"Laëtitia Milot",
"Etienne Régnier",
"Francis Boulogne",
"Gary Novak",
"Pierre André Gilard",
"Vanessa Paolini-Novak",
"Shemss Audat",
"Elsa Bailly",
"Caroline Bourg",
"Karim Fedala",
"Rachid Hafassa",
"Catherine Pujol",
"Stéphanie Daniel",
"Abdel Fedala",
"Marwan Berreni",
"Ophélie Maignan",
"Laurie Iversen",
"Elisa",
"Marylou Salvatori",
"Nisma Bailly",
"Ella Philippe",
"Bilal Bailly",
"Zacharia El Baialy",
"puis Kjet Bennet",
"Jocelyn Sandré",
"Jean-Marie Galey",
"Yolande Sandré",
"Elisabeth Commelin",
"Jean-François Leroux",
"Jean-François Malet",
"Elisabeth Babeth Nebout",
"Marie Réache",
"Patrick Nebout",
"Jérôme Bertin",
"Grégoire Vinci",
"Martin Barlan",
"Manon Gardin",
"Julianna Vogt",
"Emilie Leroux",
"Charlie Joirkin",
"Laurie Bordesoules",
"Léa Leroux",
"Charlotte Deysine",
"puis",
"Marie Hennerez",
"Valentin Nebout",
"Louis Duneton",
"Amandine Turpin",
"Ana Ka",
"Philippe Boher",
"Pierre Chevalier",
"Jean-Paul Boher",
"Stéphane Henon",
"Samia Nassri",
"Fabienne Carat",
"Hadrien Walter",
"Guillaume Delorme",
"Andrès Galeano",
"alias Pavel",
"Laurent Hennequin",
"Lucie Boher",
"Lana et Lee Lou Pubil Santiago",
"puis Camélia et Jailys Medjoub",
"puis par Romane Libert 03/2019",
"Irina Kovalev",
"Sacha Tarantovich",
"Wanda Legendre",
"Pascale Roberts",
"Blanche Marci",
"Cécilia Hornus",
"Coralie Blain",
"Sarah Mortensen",
"sept19 Coralie Audret",
"Franck Ruiz",
"Jean-Charles Chagachbanian",
"Alice Ruiz",
"Mélanie Guth",
"Johanna Marci",
"Dounia Coesens",
"Noé Ruiz",
"Eliot De Faria puis",
"Florian Lesieur",
"Emma Rimez",
"Pauline Bression",
"Camille Rimez",
"Lisa Cipriani",
"Jacob",
"Christophe Morillon",
"Charles Frémont",
"Alexandre Fabre",
"Céline Frémond",
"Rebecca Hampton",
"Vivien Dupuis",
"Michaël Erpelding",
"Djawad Sangha",
"David Baiot",
"Estelle Cantorel",
"Elodie Varlet",
"Noham Zimmer",
"Mohamed Hicham",
"Anémone Vitreuil",
"Anne Canovas",
"Thierry Delport",
"Yves Lambrecht",
"Jeanne Carmin",
"Stéphanie Pareja",
"Vincent Chaumette",
"Serge Dupire",
"Elise Carmin",
"Zara Prassinot",
"Julio Secoti",
"Samuel Charle",
"Caroline Fava",
"Diane Robert",
"Guillaume Leserman",
"Virgile Bayle",
"Sara Douala",
"Nadège Beausson-Diagne",
"Constance Dorléac",
"Valentine-Atlan",
"Anne Olivieri",
"Marie Daguerre",
"Nathan Leserman",
"Thibaut Vaneck",
"Éric Norman",
"Régis Maynard",
"Brigadier Eric Berthier",
"Eric Pessey",
"Matthieu Lombard",
"Julien Courbey",
"Wendy Lesage",
"Céline Vitcoq",
"Seta Malkavian",
"Gladys Cohen",
"Sacha Malkavian",
"Avy Marciano",
"Rochat",
"Charles Schneider",
"Yvonne Rochat",
"Anne-Marie Ponsot",
"Jonas Malkavian",
"Geoffrey Pietle",
"Layla Haddad",
"Sonya Salem",
"César Cordonnier",
"Grant Lawrens",
"Alice",
"Daphné Bonneton-Suner",
"Jérôme Belesta",
"Laurent Orry",
"Laetitia Belesta",
"Caroline Riou",
"Sébastien Leduc",
"Julien Meunier",
"M. Kemal",
"Kamel Abdelli",
"père de Fatiha Kemal",
"lave le linge du Celeste",
"Kevin Belesta",
"Théo Bertrand",
"Lylou",
"Julia-Gourand",
"Fatiha Kemal",
"Nadia Zeddam",
"Benoit Cassagne",
"Ludovic Baude",
"Agnès",
"Garance Thenault",
"Eve Tressere",
"Charley Fouquet",
"Stéphane Prieur",
"Stéphane Bierry",
"Pauline Prieur",
"Lucie-Rébéré",
"Zoé Prieur",
"Marie Drion",
"Marine Castaing",
"Margaux Devy",
"Sabrina Gocelin",
"Eléonore Sarrazin",
"Romain Vidal",
"Simon Ehrlacher",
"Philippe Duchêne",
"Xavier Thiam",
"Clément Bommel",
"David Marchal",
"Delphine Bommel",
"Delphine Rollin",
"Théo Bommel",
"Jules Fabre",
"Clara / Antoine Bommel",
"Enola Righi",
"Mouss Bonghor",
"Boubacar Kabo",
"Eugénie Grangé",
"Lara Menini",
"Ariane Hersant",
"Lola Marois-Bigard",
"Ninon Chaumette",
"Aurélie Vaneck",
"Nicolas Berger",
"Bruce Tessore",
"William Galien",
"Thomas Grascoeur",
"Elias Barrazi",
"Marco Horanieh",
"Père Alexandre",
"François-Dominique Blin",
"Maud Grangé",
"Jeanne-Marie Ducarre",
"Victoire Lissajoux",
"Flavie Péan",
"Xavier Revel",
"Grégory Questel",
"Professeur Klein",
"Olivier Cruveiller",
"Julie Lapierre",
"Marlène Rabinel",
"Maria Noguerra",
"Claire Lang",
"Emmanuel « Manu » Blain",
"Simon Coutret",
"Luis Careille",
"Grégoire Paturel / Grégoire Plantade",
"Mathis Cottereau",
"Thomas Corver",
"Mathias Desprez",
"Edouard Collin",
"Doumé Verdi",
"Teddy Candela",
"Sonia Lagari",
"Pauline Paolini",
"Tony Mercier alias Jimmy Moon",
"David van Severen",
"Alexandra Neuville",
"Eléa Clair",
"Christophe Servier",
"Jean-Luc Porraz",
"Marc Alibert",
"éric Perez",
"Anton",
"Guéro",
"Zora Dembélé",
"Virginie Emane",
"Carole Leconte",
"Lani Sogoyou",
"Alan Derval",
"Vincent Pacquot",
"Amélie Lejeune",
"Marion Pejon",
"Mathis Marci",
"Adrien & Mathis Garabedian",
"Amine Meziane",
"Mohamed Bouaoune",
"Latifa Meziane",
"Soria Moufakkir",
"Mlle Péchaud",
"Fannie Lineros",
"Claire Richet",
"Annie Gregorio",
"Juge Perrin",
"Jean-Pierre Cormarie",
"Juge Pascal Senghor",
"Rudy Mayoute",
"Nadine Pellerin",
"Myriam Bourguignon",
"juge Colbert",
"Nathalie Mann",
"Chris Poncet",
"Benjamin Richardot",
"Anne Quercy",
"Annie Milon",
"Cyril Rochat",
"Frédéric Dockes",
"Cécilia Signac",
"Marie Bouvet",
"Marc Signac",
"Renan Carteaux",
"Laura Tiernay",
"Diem Nguyen",
"M. Tourlac",
"David Bailleron",
"Joris Kresker alia Hector",
"Clément Paul Lhuaire",
"Angela Blétéritch",
"Sophie Barjac",
"Aurélie Blétéritch",
"Marion Christmann",
"Boubou",
"Thomas Brice",
"Mario",
"Yanis Richard",
"Olga",
"Julie Sassoust",
"Sandy",
"Charlie Loiselier",
"Lucas",
"Cyril Lopez",
"Mélissa Caprini",
"Claire-Aurore Bartolo",
"Hugo Dautret",
"Valentin Girma",
"Laurent Dautret",
"Michael Maïno",
"Dimitri",
"Jonas Ben Ahmed",
"Issa",
"Willis-Andy Sense",
"Christophe Ford",
"Gaetan Wenders",
"Ian Moss",
"Matt Mella",
"Samantha Hazard",
"Mélissa Silveira",
"Octave",
"Victor Bonneau Bergougnoux",
"Elodie Launay",
"Djinda Kane",
"Bastien Rondo",
"Benoît Thiebault",
"Catano Libérati",
"Daniel Hederich",
"Lisandru Libérati",
"Valentin Papoudof",
"Matéo Libérati",
"Thierry Barbet",
"Stan Mercier",
"Cyril Durel",
"Sophie Ronsard",
"Alika Del Sol",
"Alpha Sidibé",
"Vincent Vermignon",
"Julien Cayrol",
"Sébastien Agius",
"Mitia(Léonard Prain",
"Béatrice",
"Isabelle Desplantes",
"Blandine Souzon",
"Candice Dufau",
"Hélène Trésard-Bornand",
"Fanny Guidecoq",
"Martin Trésard",
"Julien Ellenrieder",
"Alison Valle",
"Myra Tyliann",
"Mila Valle",
"Malika Alaoi",
"Jennifer Valle",
"Sahra Daugreilh",
"Luce « Shine » Bastia",
"Eloïse Valli",
"Sydney Carlin",
"Elie Kaempfen",
"Nouveau petit ami de Jenny, l'ex de Kévin",
"Chloé",
"Marie-Caroline Legarrec",
"Raphaël Cortez",
"Gwendal Anglade",
"Yohan Cortez",
"Max Geller",
"Max Crozier",
"Aliocha Itovich",
"Stéphane Pitti",
"Jenny Chanez",
"Athéna Zelcovich",
"Bruno Delitto",
"Nicolas Fine",
"Eddie Delitto",
"Camille Bossard",
"Angèle Lisieux",
"Jeanne Pajon",
"Fabio",
"Jules Dousset",
"Gilles Faro",
"Vincent Desprat",
"Vanessa Ferri",
"Emmanuelle Fernandez",
"Elodie Wallace",
"Bertrand Garcin",
"Milo Djurovic",
"Samir Guelma",
"Afif Ben Badra",
"Gustave",
"Vinicius Timmerman",
"Jarvis Jones",
"Barnaby Apps",
"Paul Simonian",
"éric Defosse",
"Mme Keller",
"Hélène Milano",
"Jordan Lallier",
"Nathan Parent",
"Judith Marini",
"Anne-Laure Gruet",
"Nell",
"Héloïse Adam",
"Rémi",
"Samuel Allain Abitbol",
"Florence",
"Emmanuelle Fernandez",
"Fabienne Sera",
"Delphine Braillon",
"Dr Julien Kaplan",
"Lionel Auguste",
"Stéphanie Vaillant",
"Clémence Camus",
"Simon Varnier",
"Matthieu Loos",
"Adjoint du commandant Ferri de la DGSI",
"Iris Verdon",
"Elodie Rouprêt",
"Julien Barrault",
"Renaud Dehesdin",
"William Caro",
"Grégory Barco",
"René Didot",
"Julien Cafaro",
"Yves Garnio",
"Cyril Aubin",
"Anton Kiev",
"Stan Iankow",
"Alex Melmont",
"Aliocha Itovich",
"Jade Miller",
"Manon Elezaar",
"Joachim Passeret",
"Robin Barde",
"Olivia Passeret",
"Elsa Maure",
"Compagne de Joachim",
"Claudia Roux",
"Anne-Valérie Soler",
"Arthur Simonin alias Milan Stern",
"Quentin Augier",
"Gaëtan Vega",
"Joachim Passeret",
"Romain Parizot",
"Joseph Verdi",
"Thierry Pietra",
"Jean Lougane",
"Jean-Luc Borras",
"Maire de l'arrondissement du Mistral",
"Rousset",
"Jean Baptiste Seckler",
"Angélique Prigent",
"Léa Dauvergne",
"Fanny",
"Prudence Leroy",
"Betty Solano",
"Horya_Benabet",
"Rayane Bardet",
"Nicolas Bourgasser",
"Kendji",
"Anh Hao",
"Armand Bellefroid",
"Jean-Louis Bizet",
"Christophe Heraut",
"Justine",
"Maelli Kervoelen",
"Malika Fares",
"Leslie Bevillard",
"Rose Bertrand",
"Flora Bourne-Chastel"]
new_list = []

print("Recherche de doublon ...")

for i in nbrListe : 
	if i not in new_list: 
		new_list.append(i)
	else:
		trouve = True
		print(i)
		NbDoublon+=1
if not trouve :
	print("Aucun doublon trouvé")
else:
	print(str(NbDoublon)+" doublon(s) trouvés")
