BOARD_TAG    = uno
MONITOR_PORT  = /dev/ttyACM0

ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ../
AVR_TOOLS_DIR = /usr

AVRDDUDE     = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

include ../Arduino.mk
